server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.99.101:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.99.101
    username: guest
    password: guest
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 # 10秒不发就过期
    lease-renewal-interval-in-seconds: 5 # 每隔5秒一次心跳

