server:
  port: 8081
spring:
  application:
    name: leyou-service
  datasource:
    url: jdbc:mysql:///hm49?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: 192.168.99.101
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
logging:
  level:
    com.leyou: debug